POST http://localhost:8080/events
Content-Type: application/json

{
    "name": "test-event2",
    "description": "event-description2",
    "location": "test-location2",
    "dateTime": "2025-08-29T17:25:00.000Z"
}
