POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdWdhdEBnbWFpbC5jb20iLCJleHAiOjE3NTY5MTg4NDIsInVzZXJJZCI6MX0.XptmlruFx1wfswwF3Fa4cnpEQWranmewB2rAFRf1P2s

{
    "name": "test-event",
    "description": "event-description",
    "location": "test-location",
    "dateTime": "2025-08-29T17:25:00.000Z"
}
